spring:
  application:
    name: AUTH
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://localhost:5432/rentoome
    username: postgres
    password: megatim
    driverClassName: org.postgresql.Driver
  sql:
    init:
      platform: postgres
      
  springdoc:
    api-docs:
        path: /api-docs


# Discovery Server Access
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8777/eureka/

server:
  port: 8780

jwt:
  private.key: classpath:app.key
  public.key: classpath:app.pub

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO
#    org.springframework.boot.autoconfigure: DEBUG

auth:
    app:
        jwtSecret: ======================BezKoder=Spring===========================
        jwtExpirationMs: 86400000