spring:
  application:
    name: GATEWAY
  cloud:
    gateway:
      routes:
        - id: AUTH
          uri: http://localhost:8780/auth
          predicates:
            - Path=/api/v1/auths/**
        - id: PROPERTY-SERVICE
          uri: http://localhost:8785/PROPERTY-SERVICE
          predicates:
            - Path=/api/v1/property-service/**    
    
    # Discovery Server Access
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8777/eureka/

server:
  port: 8781

