spring:
  application:
    name: PROPERTY-SERVICE
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://localhost:5432/rentoome
    username: postgres
    password: megatim
    driverClassName: org.postgresql.Driver
  sql:
    init:
      platform: postgres
      
  springdoc:
    api-docs:
        path: /api-docs


# Discovery Server Access
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8777/eureka/

server:
  port: 8785
